### ISSUE TITLE
Docker 容器如何持久化测速结果？

### ISSUE THREAD

**Issue by ClarkeCheng** [BadApple9/speedtest-x#21]
README.md 里没有说明 Docker 容器挂载哪个文件夹才能持久化测速结果。导致我现在只要删除容器再启动，测速结果就全部没有了。请问要挂载哪个文件夹？

**Comment by BadApple9** [comment]
目前每个容器的测速结果会持久化到宿主机里容器对应的 volume 里。

也就是说，容器不销毁的话，数据也不会丢。容器若销毁重建，同时会重建 volume，所以持久化结果会被一并删除。

**Comment by Xue-JW** [comment]
假如docker-compose.yml在/opt/speedtest-x

docker-compose.yml内容如下：
```
version: '3'
services:
  speedtest-x:
    image: badapple9/speedtest-x
    restart: unless-stopped
    environment:
      SAME_IP_MULTI_LOGS: "true"
    ports:
      - "9004:80"
    volumes:
      - "./entrypoint.sh:/entrypoint1.sh"
      - "./speedlogs:/var/www/html/backend/speedlogs/"
    entrypoint: /entrypoint1.sh
```
在该目录创建一个entrypoint1.sh，内容如下：

```
#!/bin/bash

set -e
set -x

# Cleanup
#rm -rf /var/www/html/*



# Copy frontend files
cp /speedtest/*.js /var/www/html/
cp /speedtest/*.html /var/www/html/

#######修改部分#######
cp -r /speedtest/backend/. /var/www/html/backend/
cp -r /speedtest/chartjs/. /var/www/html/chartjs/

ln -snf /var/www/html/backend/speedlogs /speedlogs

mkdir -p  /var/www/html/backend/speedlogs/cache
mkdir -p /var/www/html/backend/speedlogs/data
touch /var/www/html/backend/speedlogs/_cnt.sdb
#######修改部分#######

chown -R www-data:www-data /var/www/html/*

# Allow selection of Apache port for network_mode: host
if [ "$WEBPORT" != "80" ]; then
  sed -i "s/^Listen 80\$/Listen $WEBPORT/g" /etc/apache2/ports.conf
  sed -i "s/*:80>/*:$WEBPORT>/g" /etc/apache2/sites-available/000-default.conf
fi

if [ "$MAX_LOG_COUNT" != "100" ]; then
  sed -i "s/^const MAX_LOG_COUNT = 100/const MAX_LOG_COUNT = $MAX_LOG_COUNT/g" /var/www/html/backend/config.php
fi

if [ "$IP_SERVICE" != "ip.sb" ]; then
  sed -i "s/^const IP_SERVICE = 'ip.sb'/const IP_SERVICE = '$IP_SERVICE'/g" /var/www/html/backend/config.php
fi

if [ "$SAME_IP_MULTI_LOGS" != "false" ]; then
  sed -i "s/^const SAME_IP_MULTI_LOGS = false/const SAME_IP_MULTI_LOGS = $SAME_IP_MULTI_LOGS/g" /var/www/html/backend/config.php
fi

echo "Done, Starting APACHE"

# This runs apache
apache2-foreground
```

在/opt/speedtest-x 目录输入sudo docker-compose up -d启动，数据保存在该目录speedlogs中
